# Generated by Django 4.2 on 2023-04-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=256, verbose_name='작성자')),
                ('post_title', models.CharField(max_length=45, verbose_name='글제목')),
                ('post_content', models.TextField(verbose_name='글내용')),
                ('post_img', models.FileField(upload_to='igmsns/static/post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posting',
            },
        ),
    ]
