# Generated by Django 4.2 on 2023-04-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
