# Generated by Django 4.1.7 on 2023-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.CharField(default='', max_length=15),
        ),
    ]
